apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: neo4j-community
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Neo4j Community Edition
    version: latest
    actuationTool:
      flavor: Terraform
      version: ">= 1.2"
    description:
      tagline: The world's leading graph database platform
      detailed: |-
        Neo4j Community Edition is a robust graph database designed for building applications.
        
        Key features include:
        - Clustering for high availability and scalability
        - Advanced security features
        - Monitoring and management tools
        - LDAP/Active Directory integration
        - Hot backups
        - Multi-data center support
    softwareGroups:
      - type: SG_OS
        software:
          - title: rhel-9
            version: v20260114
  content: {}
  interfaces:
    variables:
      - name: project_id
        description: The ID of the project in which to provision resources.
        varType: string
        required: true
      - name: goog_cm_deployment_name
        description: The name of the deployment and VM instances.
        varType: string
        required: true
      - name: region
        description: The region for the solution to be deployed.
        varType: string
        defaultValue: us-central1
      - name: zones
        description: The zones for the solution to be deployed.
        varType: list(string)
        defaultValue: ["us-central1-a", "us-central1-b", "us-central1-c", "us-central1-f"]
      - name: password
        description: Password for the Neo4j admin user
        varType: string
        required: true
      - name: machine_type
        description: The machine type to create
        varType: string
        defaultValue: n4-standard-4
      - name: disk_size
        description: Size of the data disk in GB
        varType: integer
        defaultValue: 100
      - name: source_image
        description: The image name for the disk for the VM instance.
        varType: string
        defaultValue: projects/neo4j-mp-public/global/images/neo4j-community-edition
    outputs:
      - name: neo4j_http_url
        description: URL to access Neo4j Browser via load balancer
      - name: neo4j_bolt_endpoint
        description: Bolt endpoint for Neo4j connections via load balancer
