apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: neo4j-enterprise-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  ui:
    input:
      variables:
        project_id:
          name: project_id
          title: Project ID
          invisible: true
        goog_cm_deployment_name:
          name: goog_cm_deployment_name
          title: Deployment Name
        region:
          name: region
          title: Region
          xGoogleProperty:
            type: ET_GCE_REGION
        zones:
          name: zones
          title: Zones
          xGoogleProperty:
            type: ET_GCE_ZONES
        password:
          name: password
          title: Password
          subtext: Password for the Neo4j admin user
          tooltip: The password must be at least 8 characters long
          regexValidation: ^.{8,}$
          validation: The password must be at least 8 characters long
        node_count:
          name: node_count
          title: Number of nodes
          subtext: Number of Neo4j nodes to deploy
          tooltip: Node count must be 1 (standalone) or 3/5/7 (cluster)
          enumValueLabels:
            - label: "1"
              value: "1"
            - label: "3"
              value: "3"
        machine_type:
          name: machine_type
          title: Machine type
          xGoogleProperty:
            type: ET_GCE_MACHINE_TYPE
            zoneProperty: zone
            gceMachineType:
              minCpu: 4
              minRamGb: 16
        disk_size:
          name: disk_size
          title: Disk size in GB
          max: 10000
          section: storage
        source_image:
          name: source_image
          title: Image version
          enumValueLabels:
            - label: neo4j-enterprise-edition
              value: projects/neo4j-mp-public/global/images/neo4j-enterprise-edition
          xGoogleProperty:
            type: ET_GCE_DISK_IMAGE
